"""empty message

Revision ID: 5fb78bd63aad
Revises: 
Create Date: 2025-11-07 12:07:23.974709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb78bd63aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('country_city', sa.String(length=280), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('embers', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_day', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('mind', sa.Integer(), nullable=False),
    sa.Column('productivity', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('social', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_followed_id', sa.Integer(), nullable=False),
    sa.Column('user_that_follows_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_that_follows_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('time_to_start', sa.String(length=300), nullable=True),
    sa.Column('recovery_time', sa.DateTime(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('habit', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.Column('mind', sa.Integer(), nullable=True),
    sa.Column('productivity', sa.Integer(), nullable=True),
    sa.Column('creativity', sa.Integer(), nullable=True),
    sa.Column('social', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('follower')
    op.drop_table('user')
    # ### end Alembic commands ###
