"""empty message

Revision ID: 880fb747d5fa
Revises: 099d29ddff09
Create Date: 2025-11-03 15:37:00.488265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880fb747d5fa'
down_revision = '099d29ddff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('time_to_start', sa.String(length=300), nullable=True),
    sa.Column('recovery_time', sa.DateTime(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('habit', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.Column('mind', sa.Integer(), nullable=True),
    sa.Column('productivity', sa.Integer(), nullable=True),
    sa.Column('creativity', sa.Integer(), nullable=True),
    sa.Column('social', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=280), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country_city', sa.String(length=280), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mind', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('productivity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creativity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('social', sa.Integer(), nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('social')
        batch_op.drop_column('creativity')
        batch_op.drop_column('productivity')
        batch_op.drop_column('mind')
        batch_op.drop_column('body')
        batch_op.drop_column('level')
        batch_op.drop_column('country_city')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    op.drop_table('task')
    # ### end Alembic commands ###
